# Generated by Django 4.1.3 on 2022-12-24 08:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=63, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=63, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('instagram_username', models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя пользователя в инстаграме')),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Участник',
            },
        ),
    ]
