# Generated by Django 4.1.3 on 2022-11-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='instagram_username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя пользователя в инстаграме'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
    ]
