# Generated by Django 4.1.3 on 2023-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('participant', '0002_remove_participant_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photos',
            field=models.ManyToManyField(to='attachments.attachments'),
        ),
    ]
