# Generated by Django 4.1.3 on 2022-12-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyclick', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicktransaction',
            name='participant',
        ),
        migrations.AddField(
            model_name='clicktransaction',
            name='participant_data',
            field=models.JSONField(default=dict),
        ),
    ]
